import type {Metadata} from "next";
import {Geist, Geist_Mono, Noto_Sans} from "next/font/google";
import "./globals.css";
import {ThemeProvider} from "@/components/theme-provider";
import React from "react";
import Navbar from "@/components/navbar";
import Footer from "@/components/footer";

const notoSans = Noto_Sans({variable: '--font-sans'});

const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
});

const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
                                       children,
                                   }: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en" className={notoSans.variable}>
        <body
            className={`${geistSans.variable} ${geistMono.variable} font-sans flex flex-col min-h-screen antialiased suppressHydrationWarning`}
        >
        <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
        >

            <header>
                <Navbar/>
            </header>

            <main className="flex-1 flex justify-center items-center">
                {children}
            </main>

            <footer>
                <Footer/>
            </footer>
        </ThemeProvider>
        </body>
        </html>
    );
}
